globalThis.facebookURL = "#";
globalThis.PinterestURL = "https://www.pinterest.com/hayeslummy";
globalThis.twitterURL = "#";
globalThis.redditURL = "#";
globalThis.siteUrl = "https:\/\/www.lummyrecipes.com";
globalThis.homepageTitle = "Lummy Recipes";
globalThis.homepageTagline = "Lummy Recipes - Discover delicious recipes for every occasion";
globalThis.email = 'contact@lummyrecipes.com';
globalThis.copyright = "2025 - 2026 Lummy Recipes. All rights reserved.";
