globalThis.facebookURL = "#";
globalThis.PinterestURL = "https://www.pinterest.com/hayeslummy";
globalThis.twitterURL = "#";
globalThis.redditURL = "#";
globalThis.siteUrl = "https:\/\/www.lummyrecipes.com";
globalThis.homepageTitle = "";
globalThis.homepageTagline = "";
globalThis.email = 'contact@lummyrecipes.com';
globalThis.copyright = "2025 - 2026 . All rights reserved.";
